# Generated by Django 5.0.2 on 2024-03-15 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='course',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='year_level',
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='short_bio',
            field=models.TextField(default=None),
        ),
    ]
